local anime_sec={0.1,0.2};
return Def.ActorFrame{
	InitCommand=function(self)
		--self:x(SCREEN_WIDTH-100);
		--self:y(SCREEN_HEIGHT-100);
		self:Center();
		self:addy(-10);
	end;
	LoadActor("_frame")..{
		InitCommand=function(self)
			self:zoom(0);
		end;
		BeginCommand=function(self)
			self:diffusealpha(0);
			self:zoom(2);
			self:linear(anime_sec[1]);
			self:diffusealpha(1);
			self:zoom(1);
			self:rotationy(0);
			self:linear(anime_sec[1]);
			self:rotationy(360);
		end;
	};
	LoadActor("_under")..{
		InitCommand=function(self)
			self:zoom(0);
			self:blend("BlendMode_Add");
		end;
		BeginCommand=function(self)
			self:sleep(anime_sec[1]*2);
			self:zoom(0);
			self:bounceend(anime_sec[2]);
			self:zoom(1);
		end;
	};
	LoadActor("_over")..{
		InitCommand=function(self)
			self:zoom(0);
		end;
		BeginCommand=function(self)
			self:sleep(anime_sec[1]);
			self:zoom(0);
			self:linear(anime_sec[1]);
			self:zoom(1);
		end;
	};
	LoadActor("_text")..{
		InitCommand=function(self)
			self:zoom(0);
		end;
		BeginCommand=function(self)
			self:sleep(anime_sec[1]);
			self:diffusealpha(0);
			self:zoom(4);
			self:linear(anime_sec[1]);
			self:diffusealpha(1);
			self:zoom(1);
		end;
	};
};